### ISSUE TITLE
Test reliability and performance of state recording in state tracker on receiving a large number of messages

### ISSUE THREAD

**Issue by justincc** [HumanCellAtlas/ingest-central#315]
Acceptance criteria

- [ ] Create code that can test core and state tracker in isolation from other ingest components such as ingest
- [ ] Test core + state tracker with a large number of incoming messages to simulate a large load flowing through the validator
- [ ] Make it easy to run these tests
- [ ] Run this test periodically
- [ ] Record this test in the [dev test master doc](https://docs.google.com/document/d/1PHdipZM4KB94Q-4vsQ2BCrmDA4_SoeVVBSJNQnD_u5o/)

**Comment by aaclan-ebi** [comment]
PR: https://github.com/HumanCellAtlas/ingest-integration-tests/pull/6

**Comment by aaclan-ebi** [comment]
tests_big_submission job is now running in dev, integration, staging
https://allspark.dev.data.humancellatlas.org/HumanCellAtlas/ingest-integration-tests/pipelines

**Comment by justincc** [comment]
Thanks Alegria. Let's move to done but not close until end of iteration. This is how I track what got done in that iteration :)
