### ISSUE TITLE
Test performance of ingest core and state tracker in isolation from other components

### ISSUE THREAD

**Issue by justincc** [HumanCellAtlas/ingest-central#316]
Acceptance criteria:
- [ ] Run test with 4000 bundles (same as current DCP wide but should ultimately probably be more)
- [ ] Use this test to assess an infrastructure change where we remove internal queues from ingest core
- [ ] Record this test in the [ingest dev test master doc](https://docs.google.com/document/d/1PHdipZM4KB94Q-4vsQ2BCrmDA4_SoeVVBSJNQnD_u5o/edit#heading=h.t5k1gq3hbdab)

**Comment by justincc** [comment]
Dupe of #315 in the end
